### ISSUE TITLE
During setup, Chromium requesting to run as root

### ISSUE THREAD

**Issue by cjmcqueen** [KanoComputing/kano-settings#203]
Getting a Chromium error during setup, making it difficult to setup a profile on first run.
![kano-chromium-error](https://cloud.githubusercontent.com/assets/128125/5554811/58bdfec4-8c2c-11e4-8ef0-bc536c6c1385.jpg)

**Comment by alex5imon** [comment]
WiFi settings has changed now into a GUI based tool.

**Comment by Vanhealen** [comment]
So how are you supposed to get passed this issue? I am facing it as well.

**Comment by alex5imon** [comment]
@Vanhealen please install the latest version following [these steps](https://help.kano.me/hc/en-us/articles/207213475-Re-install-Kano-OS-using-NOOBs-Recommended-)
