### ISSUE TITLE
Adding localization for portuguese

### ISSUE THREAD

**Issue by g-guth** [KanoComputing/kano-settings#413]
Hi, I would like to translate the **kano-settings** app to portuguese. I would like to know what is the best way to do that, is there some localization config or resource file that i can create to make it easily? 
Thanks!

**Comment by Ealdwulf** [comment]
Yes, there is a directory here: https://github.com/KanoComputing/kano-settings/tree/master/po containing the text. 
We don't seem to have copied the instructions into this repo, but they are the same as these ones:
https://github.com/KanoComputing/terminal-quest/blob/master/TRANSLATION.md
Thanks for your interest!

**Comment by g-guth** [comment]
I made it following your links, thanks! But i cannot find how to do the same with the kano-settings lxde plugin on the lxpanel, it seems that this c program doesnt use the .mo file.

**Comment by Ealdwulf** [comment]
Yes, it looks like we haven't internationalised that one yet. So it would require changing the code in this file: https://github.com/KanoComputing/kano-settings/blob/master/lxpanel-plugin/kano_settings.c
I'm not sure when we are likely to get to that.

**Comment by g-guth** [comment]
Great, thanks.
