### ISSUE TITLE
WiFi Driver

### ISSUE THREAD

**Issue by pixelflowxyz** [KanoComputing/kano-settings#507]
Hey there,

Posting here as it's where the Wiki page is for the Kano WiFi adapter.
I'm trying to use the adapter on a Windows PC, and can't find the drivers for the green WiFi adapter that came with the original (Kickstarter edition!) Kano kit, with the Pi 1B etc.
I've discovered a '_manual_' for it, but it doesn't seem legit - [here](https://fccid.io/2ACVK-15G7000B/User-Manual/User-manual-2897447.iframe) - and that links to a Mediatek page that doesn't work.

Would love any help,
-Dan

**Comment by Ealdwulf** [comment]
Well, the one we shipped most of the time was a `Ralink Technology, Corp. RT5370 Wireless Adapter`, not Mediatek. I'm not sure that was the one which went out with the original kickstarter kits, but it probably was. If you still have your pi, you can run plug it in `lsusb` and it will tell you what it is. 

Oh, it seems like Ralink got bought by Mediatek. In which case, this may be the driver: https://www.mediatek.com/products/broadbandWifi/rt5370
Obviously we don't support windows, so I haven't tried it. Good luck!
