### ISSUE TITLE
[Audio] Switch to HDMI not working in 4.1.0

### ISSUE THREAD

**Issue by DarknessChild** [KanoComputing/kano-settings#527]
When switching the default audio output in Kanux 4.1.0 Beta on Kano Pi 3b kit, even when HDMI is selected, output is through analog.

**Comment by idesignstuff** [comment]
Me too

**Comment by yeshpi** [comment]
Please refer this link for the solution https://github.com/KanoComputing/kano-settings/issues/532#issuecomment-774541195
